"""
Step 4c: Merge LoRA adapters into base weights → single inference checkpoint
Run:  python train/merge.py

After merge, the model runs with zero adapter overhead — same speed as base.
This is the artifact that gets published to HuggingFace under CC-BY-SA 4.0.
"""
import torch
from pathlib import Path
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel

DPO_CKPT    = Path("checkpoints/dpo_v1")
MERGED_CKPT = Path("checkpoints/merged_final")

def main():
    MERGED_CKPT.mkdir(parents=True, exist_ok=True)
    print("Loading base model in BF16 on CPU (avoids quantization artifacts in merged weights)...")

    base = AutoModelForCausalLM.from_pretrained(
        "meta-llama/Llama-3.1-8B-Instruct",
        revision="8c22764",
        torch_dtype=torch.bfloat16,
        device_map="cpu",          # merge on CPU to avoid VRAM overflow
    )

    print(f"Loading DPO adapters from {DPO_CKPT}...")
    model = PeftModel.from_pretrained(base, str(DPO_CKPT))

    print("Merging adapters into base weights...")
    merged = model.merge_and_unload()

    print(f"Saving merged model to {MERGED_CKPT}...")
    merged.save_pretrained(str(MERGED_CKPT), safe_serialization=True)
    AutoTokenizer.from_pretrained(DPO_CKPT).save_pretrained(str(MERGED_CKPT))

    # Write a model card for HuggingFace upload
    card = """---
license: cc-by-sa-4.0
base_model: meta-llama/Llama-3.1-8B-Instruct
tags:
  - fine-tuned
  - qlora
  - dpo
  - knowledge-base
  - it-operations
---

# ResolveIQ — IT Micro-Postmortem Generator

Fine-tuned from `meta-llama/Llama-3.1-8B-Instruct` using QLoRA SFT + DPO
to generate structured enterprise IT knowledge base articles from incident
resolution threads.

## Output format
Four-section Micro-Postmortem: Issue Summary, Root Cause, Resolution Steps,
Prevention and Action Items.

## Training data
Stack Exchange Server Fault data dump (CC-BY-SA 4.0).
Synthetic targets generated by Llama-3.3-70B-Instruct (Llama 3.3 Community License).

## License
CC-BY-SA 4.0 — inherited from the Server Fault training corpus.
Upstream data source: Stack Exchange Server Fault (stackexchange.com).
"""
    (MERGED_CKPT / "README.md").write_text(card)
    print(f"\n✓ Merged model saved. Ready to serve with vLLM or transformers.")
    print(f"  Size: ~16 GB (BF16). Upload to HuggingFace with:")
    print(f"  huggingface-cli upload YOUR_HF_USER/resolveiq-8b {MERGED_CKPT}")

if __name__ == "__main__":
    main()
